export const REGISTER_FETCH_STARTED = 'REGISTER/FETCH_STARTED';
export const REGISTER_FETCH_SUCCESS = 'REGISTER/FETCH_SUCCESS';
export const REGISTER_FETCH_FAILURE = 'REGISTER/FETCH_FAILURE';

export const LOGIN_FETCH_STARTED = 'LOGIN/FETCH_STARTED';
export const LOGIN_FETCH_SUCCESS = 'LOGIN/FETCH_SUCCESS';
export const LOGIN_FETCH_FAILURE = 'LOGIN/FETCH_FAILURE';
